name: single_page_app
description: A minimal single-page Flutter app with several buttons and a top-right mic icon.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  record: ^6.1.1
  http: ^1.2.2
  audioplayers: ^6.1.0
  path_provider: ^2.1.4
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

# dependency_overrides:
#   record_platform_interface: ^1.4.0
#   record_web: ^1.2.0


